language: node_js
node_js:
- '9'
before_install:
- npm install
script:
- npm run build
after_success:
- bash .deploy.sh
branches:
  only: master
env:
  global:
    secure: ODc+OGO8Oe797CbP1lmlruZ1dyJpwiOPvB1ZDh23koGsmIofB65F/kR1ULCiGhbjZZ/vozdL+CJBGnR6R0Dm727Eq6ppxR6wobD9rT4lzexgWGyUpMu3EGhF/flL/a9UwLiLhyTTJA7JekxxoVL7Ouw+KItp74cKRHqnkRyViiFJ/T+8it0oOe7jbb2WWupQWdoeoaDkNIaAJ+kQoQmRQN7ylwNhbn0rFA6QYt4yhGVxPMsdPsbQvirOCArohtiMwm+8tg+XEDfhs4cbRTF7WvIMZHXSfd3eRaMub66egn75dgt0TyGXU1HeiXHVf05DMOBiUWfR3cAYg9UDGD3ybRgPySmhYvXJNpwrOcdQGK2sgdnGc7vSGX4Ok/Ao3vm34Y94OsnwJ7v2G8HEeBSXDsk7tg+t7E/9pFvww9c50tLcfcKC7lamUiYHB167WRxUgtU3B15HoqorndpW/JnVPrgJkNTLW0eAa8PeoUb8QgCRGpt7JHBYAg6RNSH/6gC+uvLKrNIAP/+6JnYZTDj1JbJsisHmqN7fMK3Fk1GW2yp/RRrO2d1JnhXT8tFNm+ANGaMT2TUYtqdUmpzHbSgrzKurBr1bCbmyDxHPFclbJ4c1K+5Mq5s39/2mGcI+gbBHO5pw/mtwu5lPCejt7V+iS+L1VHBw0gmBlgYyENGIY6w=
