language: node_js
node_js:
- '9'
before_install:
- npm install
script:
- npm run build
after_success:
- bash .deploy.sh
branches:
  only: master
env:
  global:
  - secure: RFmMFf4bwhDHDRNEsGoVoKnimux+zW/IPGIRG5zrqRdzNSlUyYr8sJum432wG3XQff+Ikj5GH4jdM8SC+a/BBbT0YsX+7XIZMhnv67PHe/oMyGARokpmeuLWO7jDg4x1Bxo8IpyIwE46ddchjiRkY+dDKZk804RhmDL65MJxAojpXz+MhvvgDOBMUEaAXVHtAibpUKwqQV3T9FTKl0O+lqgvQu5UgtR1Qdvr6vqUUwMpc0mmDHHfT2EnfUtqpMdPH9/QQQd2mGy8VPp+HJMLkgX76haIlKc5VQUHxfEGGOAVWnS5oCv8A6X+tln0oG0DMEOPDsSlcRdUKK+aD1SAyUhJ1GRf3l6ooq03r69aq0qyY5XnPP8r5HYmyvtqXV6v7y16gpMPD7obTUSpIZ8HZqZtFnk1+RoTE5+NPFVXGraQuC4U4UKdeByZiixnDunMYzSz4URZIHP4ASYNuwE/SwMpN8TmvxsDvLQJxeS5oiWV+X36Gk9QymlD2/1lyYPIMXBBXAxj5zc9YY2M8/wgIR9pYW7VjgG+LAq7NIB3SBuc/JozxFEYXgnTheaSHLcvhPSLjv96PMaWevdrOI2dKkGIJvUvDcYRZcRq6atcNN8l4g1qtYP6bphUU7y+Wcdg1A3bXRkEF4tvu2FsWV0iPmLz6h+p429v+zhaqMPVu1A=
